#!/usr/bin/env python3

# todo, rewrite this in C

import sys
import os

if len(sys.argv) != 5:
    print("Bad Argument Count")
    exit(1)

if sys.argv[1] != '-d' or sys.argv[3] != '-o':
    print("Unexpected Flag(s)")
    exit(1)

for FN in os.listdir(sys.argv[2]):

    if not (FN.endswith(".kbm") or FN.endswith(".KBM")):
        continue

    print(FN)

    F = open(sys.argv[2] + os.sep + FN)
    FC = F.read()

    F.close()
    del F

    name = FN[:-4].upper()

    OFN = sys.argv[4] + os.sep + "KBM_" + name + ".c"

    OFC = FC
    W = len(max(OFC.split("\n"), key=len))
    OFC = "\n".join([f'"{ln + (" "*(W-len(ln)))}"\\' for ln in OFC.split("\n")[:-1]])

    identifier = os.path.basename(OFN[:-2])

    OFC = "#define " + identifier + " \\\n" + OFC

    # Trim extra '\'
    OFC = OFC[:-1]

    OFC += "\n#define " + identifier + "_W " + str(W)
    OFC += "\n#define " + identifier + "_H " + str(FC.count("\n"))

    OF = open(OFN, "w")
    OF.write(OFC)
    OF.close()
    del OF
exit(0)
